/**
 * Central user-facing text catalog for the PosTerminal client.
 *
 * UI_STYLE_GUIDE requires every user-facing string to be Turkish and every enum
 * value to pass through a translation map. This module is the single source for
 * both, so untranslated leaks (the "Manager" case) are caught by inspecting one
 * file instead of a scanning heuristic (deep-analysis finding F-7).
 *
 * Migration is incremental: the cross-cutting text (roles, connectivity, common
 * actions, navigation) and every enum label map now live here. Feature-local
 * one-off copy is still being moved in - new strings belong here, not inline.
 */

import type { SplitMode } from "./features/billing/models";
import type { CatalogEntityKind } from "./features/catalog/models";
import type {
  KitchenBackup,
  KitchenHealthSnapshot,
  KitchenTicket,
  KitchenTicketItem,
} from "./features/kitchen-operations/models";
import type { TableAction, TableStatus } from "./features/tables/models";

/** Role labels shown in the shell. Derived from session capabilities, never from the route. */
export const roleLabels = {
  manager: "Yönetici",
  cashierOps: "Kasiyer / Operasyon",
  limited: "Sınırlı erişim",
} as const;

/** Connectivity status labels for the shell status bar. */
export const connectivityLabels = {
  online: "Çevrimiçi",
  reconnecting: "Yeniden bağlanıyor",
  offline: "Çevrimdışı",
} as const;

/** Primary navigation labels. */
export const navLabels = {
  sales: "Kasa",
  tables: "Masalar",
  billing: "Hesap",
  pendingChecks: "Bekleyen hesaplar",
  onlineFood: "Online Yemek",
  kitchen: "Mutfak",
  catalog: "Menü",
  system: "Sistem",
  authorization: "Yetki",
  management: "Yönetim",
} as const;

/** Yönetim alanı kabuğu ve Gün sonu ve mutabakat bölümü (V1-RMD-445). */
export const managementText = {
  title: "Yönetim",
  description: "Gün sonu, mutabakat ve işletme yönetimi bölümleri",
  sectionsLabel: "Yönetim bölümleri",
  noSectionTitle: "Bu oturumda açılabilir bölüm yok",
  noSectionBody: "Yönetim bölümleri için gerekli yetkilere sahip değilsiniz.",
  closing: {
    tab: "Gün sonu ve mutabakat",
    dayHeading: "İş günü",
    dateLabel: "Tarih",
    load: "Getir",
    noDay: "Bu tarih için iş günü kaydı yok.",
    openDay: "İş gününü aç",
    closeDay: "İş gününü kapat",
    closeHint: "Gelir ve sipariş sayısı sunucu tarafından kayıtlardan hesaplanır. İptal ve yazdırma hatası sayısını biliyorsanız girin; bilmiyorsanız 0 bırakın.",
    cancelledItems: "İptal edilen kalem sayısı",
    printFailures: "Yazdırma hatası sayısı",
    status: "Durum",
    openedAt: "Açılış",
    closedAt: "Kapanış",
    revenue: "Toplam ciro",
    orders: "Sipariş sayısı",
    cancelled: "İptal edilen kalem",
    printFailed: "Yazdırma hatası",
    waiters: "Garson performansı",
    waiter: "Garson",
    served: "Servis edilen sipariş",
    sales: "Satış tutarı",
    cancellations: "İptal",
    discounts: "İndirim",
    settlementHeading: "Ödeme mutabakat raporu",
    paymentMix: "Ödeme yöntemleri",
    method: "Yöntem",
    count: "Adet",
    amount: "Tutar",
    unsettled: "Sonuçlanmamış ödemeler",
    unknown: "Sonucu bilinmeyen",
    reconciliationRequired: "Mutabakat gereken",
    cashSessions: "Kasa oturumları",
    expected: "Beklenen nakit",
    actual: "Sayılan nakit",
    difference: "Fark",
    sessionOpen: "Açık",
    sessionClosed: "Kapalı",
    caseTotals: "Vaka özeti",
    caseType: "Vaka türü",
    openCases: "Açık",
    resolvedCases: "Çözülen",
    openDiscrepancy: "Açık fark",
    unavailableSections: "Bu bölümler henüz kullanılamıyor: iade net tutarı, mali durum, yemek kartı kapanışı.",
    manualHeading: "Elle onaylanan kart ödemeleri",
    slip: "Slip no",
    requestedAt: "Talep",
    decidedAt: "Karar",
    casesHeading: "Mutabakat vakaları",
    caseStatusFilter: "Vaka durumu",
    scan: "Ödeme taraması yap",
    scanDone: "Tarama tamamlandı; vaka listesi yenilendi.",
    severity: "Önem",
    opened: "Açılış",
    caseNote: "Karar notu (isteğe bağlı)",
    actions: "İşlem",
    empty: "Kayıt yok.",
    loading: "Yükleniyor…",
    loadFailed: "Veri alınamadı.",
    actionFailed: "İşlem tamamlanamadı.",
    dayOpened: "İş günü açıldı.",
    dayClosed: "İş günü kapatıldı.",
    caseUpdated: "Vaka güncellendi.",
  },
  purchasing: {
    tab: "Satın alma",
    suppliersHeading: "Tedarikçiler",
    ordersHeading: "Satın alma siparişleri",
    code: "Kod",
    name: "Ad",
    status: "Durum",
    taxNumber: "Vergi numarası",
    taxOffice: "Vergi dairesi",
    phone: "Telefon",
    email: "E-posta",
    active: "Aktif",
    passive: "Pasif",
    activate: "Etkinleştir",
    deactivate: "Pasifleştir",
    newSupplier: "Yeni tedarikçi",
    add: "Ekle",
    supplierAdded: "Tedarikçi eklendi.",
    supplierUpdated: "Tedarikçi güncellendi.",
    statusFilter: "Sipariş durumu",
    allStatuses: "Tümü",
    orderNumber: "Sipariş no",
    supplier: "Tedarikçi",
    total: "Tutar",
    actions: "İşlem",
    submit: "Gönder",
    cancel: "İptal et",
    receive: "Mal kabul",
    orderSubmitted: "Sipariş gönderildi.",
    orderCancelled: "Sipariş iptal edildi.",
    newOrder: "Yeni satın alma siparişi",
    destination: "Teslim konumu",
    notes: "Not (isteğe bağlı)",
    stockItem: "Stok kalemi",
    quantity: "Miktar",
    unitPrice: "Birim fiyat",
    addLine: "Kalem ekle",
    removeLine: "Kalemi çıkar",
    createOrder: "Siparişi oluştur",
    orderCreated: "Sipariş oluşturuldu.",
    receiptNumber: "Mal kabul no",
    delivered: "Teslim edilen",
    open: "Açık miktar",
    variance: "Fark nedeni",
    managerApproved: "Yönetici onayı",
    confirmReceipt: "Mal kabulü kaydet",
    receiptSaved: "Mal kabul kaydedildi.",
    lookupFailed: "Konum ve stok kalemleri okunamadı; sipariş formu kullanılamıyor.",
    invalidNumber: "Geçerli bir sayı girin.",
    needLines: "En az bir sipariş kalemi girin.",
    pick: "Seçin",
    empty: "Kayıt yok.",
    loading: "Yükleniyor…",
    loadFailed: "Veri alınamadı.",
    actionFailed: "İşlem tamamlanamadı.",
    close: "Kapat",
  },
  production: {
    tab: "Üretim",
    batchesHeading: "Üretim partileri",
    batchNumber: "Parti no",
    status: "Durum",
    planned: "Planlanan",
    actual: "Gerçekleşen",
    unit: "Birim",
    statusFilter: "Parti durumu",
    allStatuses: "Tümü",
    actions: "İşlem",
    start: "Başlat",
    complete: "Tamamla",
    cancel: "İptal et",
    newBatch: "Yeni üretim partisi",
    recipeVersion: "Tarif sürümü",
    plannedQuantity: "Planlanan miktar",
    portionUnit: "Porsiyon birimi",
    create: "Partiyi oluştur",
    batchCreated: "Parti oluşturuldu.",
    batchStarted: "Parti başlatıldı.",
    batchCompleted: "Parti tamamlandı.",
    batchCancelled: "Parti iptal edildi.",
    actualQuantity: "Gerçekleşen miktar",
    sourceLocation: "Hammadde konumu",
    destinationLocation: "Ürün konumu (isteğe bağlı)",
    outputItem: "Çıktı stok kalemi (isteğe bağlı)",
    reason: "İptal nedeni (isteğe bağlı)",
    confirmComplete: "Partiyi tamamla",
    confirmCancel: "Partiyi iptal et",
    dismiss: "Vazgeç",
    none: "Yok",
    pick: "Seçin",
    noRecipes: "Etkin tarif sürümü bulunamadı; tarif tanımlanmadan parti oluşturulamaz.",
    invalidNumber: "Geçerli bir sayı girin.",
    pickLocation: "Bir konum seçin.",
    empty: "Kayıt yok.",
    loading: "Yükleniyor…",
    loadFailed: "Veri alınamadı.",
    actionFailed: "İşlem tamamlanamadı.",
  },
  menus: {
    tab: "Menüler",
    menusHeading: "Menüler",
    dailyHeading: "Günün menüsü",
    code: "Kod",
    name: "Ad",
    status: "Durum",
    actions: "İşlem",
    active: "Aktif",
    passive: "Pasif",
    activate: "Etkinleştir",
    deactivate: "Pasifleştir",
    open: "Aç",
    manage: "Kalemleri göster",
    newMenu: "Yeni menü",
    add: "Ekle",
    menuAdded: "Menü eklendi.",
    menuUpdated: "Menü güncellendi.",
    product: "Ürün",
    order: "Sıra",
    addProduct: "Menüye ürün ekle",
    productAdded: "Ürün menüye eklendi.",
    itemUpdated: "Menü kalemi güncellendi.",
    inactiveInCatalog: "Katalogda pasif",
    date: "Tarih",
    load: "Getir",
    noDaily: "Bu tarih için günün menüsü yok.",
    createDaily: "Günün menüsünü oluştur",
    note: "Not (isteğe bağlı)",
    dailyCreated: "Günün menüsü oluşturuldu.",
    openDaily: "Menüyü aç",
    closeDaily: "Menüyü kapat",
    dailyOpened: "Günün menüsü açıldı.",
    dailyClosed: "Günün menüsü kapatıldı.",
    price: "Fiyat",
    planned: "Planlanan porsiyon",
    prepared: "Hazırlanan",
    available: "Kalan",
    outOfStock: "Tükendi",
    setPrice: "Fiyatı değiştir",
    setPortions: "Porsiyonu değiştir",
    save: "Kaydet",
    cancel: "Vazgeç",
    priceUpdated: "Fiyat güncellendi.",
    portionsUpdated: "Planlanan porsiyon güncellendi.",
    addDailyItem: "Güne ürün ekle",
    priceOptional: "Fiyat (boşsa katalog fiyatı)",
    recipeOptional: "Tarif sürümü (isteğe bağlı)",
    dailyItemAdded: "Ürün günün menüsüne eklendi.",
    none: "Yok",
    pick: "Seçin",
    invalidNumber: "Geçerli bir sayı girin.",
    empty: "Kayıt yok.",
    loading: "Yükleniyor…",
    loadFailed: "Veri alınamadı.",
    actionFailed: "İşlem tamamlanamadı.",
  },
  recipeCost: {
    tab: "Tarif maliyeti",
    heading: "Tarif maliyeti",
    recipeVersion: "Tarif sürümü",
    asOf: "Geçerlilik tarihi",
    show: "Geçerli maliyeti göster",
    calculate: "Bugünkü maliyeti hesapla",
    none: "Bu sürüm için seçilen tarihte kayıtlı bir maliyet yok.",
    total: "Parti maliyeti",
    perPortion: "Porsiyon maliyeti",
    basisDate: "Maliyet tarihi",
    ingredient: "Malzeme",
    quantity: "Miktar",
    unitCost: "Birim maliyet",
    lineCost: "Tutar",
    calculated: "Maliyet hesaplandı.",
    pick: "Seçin",
    noVersions: "Tarif sürümü bulunamadı.",
    empty: "Kayıt yok.",
    loading: "Yükleniyor…",
    loadFailed: "Veri alınamadı.",
    actionFailed: "İşlem tamamlanamadı.",
  },
  staff: {
    tab: "Personel ve roller",
    createHeading: "Personel hesabı aç",
    createHint: "Yeni personel için giriş hesabı açar.",
    username: "Kullanıcı adı",
    displayName: "Görünen ad",
    password: "Parola",
    passwordHint: "En az 8 karakter.",
    create: "Hesabı aç",
    created: "Personel hesabı açıldı.",
    invalidNewUser: "Kullanıcı adı, görünen ad ve en az 8 karakterli bir parola girin.",
    findHeading: "Personel bul",
    find: "Bul",
    notFound: "Bu kullanıcı adıyla personel bulunamadı.",
    active: "Etkin",
    inactive: "Pasif",
    locked: "Kilitli",
    deactivate: "Pasifleştir",
    reactivate: "Yeniden etkinleştir",
    deactivated: "Hesap pasifleştirildi.",
    reactivated: "Hesap yeniden etkinleştirildi.",
    roles: {
      heading: "Roller ve izinler",
      usersHeading: "Personelin rolleri",
      role: "Rol",
      permissionCount: "İzin sayısı",
      permissions: "İzinler",
      actions: "İşlem",
      editPermissions: "İzinleri düzenle",
      permissionGranted: "İzin verildi.",
      permissionRevoked: "İzin geri alındı.",
      revokeQuestion: "Bu izin geri alınsın mı?",
      confirmYes: "Evet, geri al",
      confirmNo: "Vazgeç",
      newRole: "Yeni rol",
      code: "Rol kodu",
      codeHint: "Küçük harf, rakam ve tire kullanın (ör. salon-sorumlusu).",
      name: "Rol adı",
      createRole: "Rolü oluştur",
      roleCreated: "Rol oluşturuldu.",
      invalidRole: "Rol kodu (küçük harf, rakam, tire) ve rol adı girin.",
      empty: "Kayıtlı rol yok.",
      noUsers: "Kayıtlı personel yok.",
      person: "Personel",
      username: "Kullanıcı adı",
      status: "Durum",
      active: "Etkin",
      inactive: "Pasif",
      userRoles: "Roller",
      editRoles: "Rolleri düzenle",
      addRole: "Rol ekle",
      pick: "Seçin",
      assign: "Rolü ata",
      roleAssigned: "Rol atandı.",
      revokeRole: "Rolü geri al",
      revokeRoleQuestion: "Bu rol personelden geri alınsın mı?",
      roleRevoked: "Rol geri alındı.",
      unknownRole: "Tanımsız rol",
      loading: "Yükleniyor…",
      loadFailed: "Veri alınamadı.",
      actionFailed: "İşlem tamamlanamadı.",
    },
    actionFailed: "İşlem tamamlanamadı.",
  },
  security: {
    tab: "Güvenlik",
    loading: "Yükleniyor…",
    empty: "Kayıt yok.",
    loadFailed: "Veri alınamadı.",
    recovery: {
      heading: "Kullanıcı Ara",
      hint: "Oturumları sonlandırmak veya hesap kilidini kaldırmak için bir kullanıcı adı girin.",
      username: "Kullanıcı adı",
      search: "Ara",
      searching: "Aranıyor…",
      notFound: "Bu kullanıcı adıyla bir hesap bulunamadı.",
      active: "● Aktif",
      inactive: "● Devre dışı",
      locked: "● Kilitli",
      revoke: "Tüm Oturumları Sonlandır",
      unlock: "Hesap Kilidini Kaldır",
      revoked: "Tüm oturumlar sonlandırıldı ({0} oturum).",
      unlocked: "Hesap kilidi kaldırıldı.",
      failed: "İşlem tamamlanamadı.",
    },
    maintenance: {
      heading: "Bakım işleri",
      run: "Şimdi çalıştır",
      ran: "İş çalıştırıldı",
      lastRun: "Son çalışma",
      every: "her",
      disabled: "Kapalı",
      failed: "İş çalıştırılamadı.",
    },
    backup: {
      heading: "Yedekleme",
      dataClass: "Veri türü",
      target: "Hedef aralık",
      gap: "Ölçülen aralık",
      status: "Durum",
      noReceipt: "Yedek makbuzu yok",
      meets: "Hedefe uygun",
      misses: "Hedefin dışında",
      attempts: "Geri yükleme denemeleri",
      noAttempts: "Kayıtlı geri yükleme denemesi yok.",
      startedAt: "Başlangıç",
      checks: "Bütünlük denetimi",
      succeeded: "Başarılı",
      failedAttempt: "Başarısız",
    },
    backlog: {
      heading: "Eski sipariş yığını",
      live: "Açık sipariş",
      settled: "Ödemesi tamamlanmış",
      withoutBill: "Hesabı olmayan",
      withOpenBill: "Açık hesabı olan",
      oldest: "En eski ödenmiş sipariş",
      preview: "Kapatılabilecekleri göster",
      nothing: "Kapatılabilecek sipariş yok.",
      eligible: "Kapatılabilecek {0} sipariş var",
      confirm: "{0} siparişi kapat",
      closed: "Kapatılan: {0}, kapatılamayan: {1}.",
      failed: "İşlem tamamlanamadı.",
    },
    diagnostic: {
      heading: "Tanılama paketi",
      correlationIds: "Korelasyon kimlikleri",
      correlationHint: "Virgül veya boşlukla ayırın.",
      from: "Başlangıç",
      to: "Bitiş",
      reason: "Gerekçe",
      create: "Paketi oluştur",
      created: "Tanılama paketi hazırlandı.",
      invalid: "Korelasyon kimliği, tarih aralığı ve gerekçe girin.",
      summary: "{0} kayıt, {1} sağlıksız kontrol, yaklaşık {2} KB.",
      download: "Paketi indir",
      failed: "Paket hazırlanamadı.",
    },
  },
  settingsHistory: {
    tab: "Ayar geçmişi",
    heading: "Ayarlar",
    historyHeading: "Değişiklik geçmişi",
    setting: "Ayar",
    currentValue: "Şimdiki değer",
    updatedAt: "Son değişiklik",
    notes: "Not",
    actions: "İşlem",
    inactive: "Pasif",
    requiresRestart: "Yeniden başlatma gerekir",
    showHistory: "Geçmişi göster",
    when: "Zaman",
    who: "Değiştiren",
    userCode: "Kullanıcı",
    system: "Sistem",
    oldValue: "Önceki değer",
    newValue: "Yeni değer",
    reason: "Gerekçe",
    noHistory: "Bu ayar için kayıtlı değişiklik yok.",
    empty: "Kayıtlı ayar yok.",
    loading: "Yükleniyor…",
    loadFailed: "Veri alınamadı.",
  },
  channelReport: {
    tab: "Kanal raporu",
    heading: "QR ve online sipariş raporu",
    from: "Başlangıç",
    to: "Bitiş",
    channel: "Kanal",
    allChannels: "Hepsi",
    qr: "QR",
    online: "Online",
    load: "Raporu getir",
    loading: "Yükleniyor…",
    loadFailed: "Rapor alınamadı.",
    hint: "Tarih aralığını seçip raporu getirin.",
    empty: "Bu aralıkta kayıt yok.",
    invalidRange: "Başlangıç tarihi bitişten sonra olamaz ve iki tarih de seçilmelidir.",
    tooLong: "Rapor en çok 31 günü kapsayabilir.",
    unbalanced: "Rapor toplamları sipariş kayıtlarıyla tutmuyor; rakamlara güvenmeyin ve destek ile görüşün.",
    date: "Tarih",
    platform: "Platform",
    received: "Alınan",
    accepted: "Kabul",
    rejected: "Reddedilen",
    cancelled: "İptal",
    refused: "Oluşturulamayan",
    gross: "Kabul tutarı (brüt)",
    net: "Kabul tutarı (net)",
    total: "Toplam",
    notRevenue: "Bu tutarlar ciroya ve kasaya dahil değildir; online satışlar yalnız bu raporda izlenir.",
  },
  productMargin: {
    tab: "Ürün kârlılığı",
    heading: "Ürün satış maliyeti ve brüt kâr",
    from: "Başlangıç",
    to: "Bitiş",
    load: "Raporu getir",
    loading: "Yükleniyor…",
    loadFailed: "Rapor alınamadı.",
    hint: "Tarih aralığını seçip raporu getirin.",
    empty: "Bu aralıkta kayıt yok.",
    invalidRange: "Başlangıç tarihi bitişten sonra olamaz ve iki tarih de seçilmelidir.",
    tooLong: "Rapor en çok 31 günü kapsayabilir.",
    unbalanced: "Rapor toplamları fiş kayıtlarıyla tutmuyor; rakamlara güvenmeyin ve destek ile görüşün.",
    unknownWarning: "Maliyeti bilinmeyen satır sayısı (ilgili hammaddeye alış kaydı girilmemiş):",
    product: "Ürün",
    sold: "Satılan",
    givenAway: "İkram",
    revenue: "Net satış",
    cost: "Maliyet",
    margin: "Brüt kâr",
    marginPercent: "Kâr oranı",
    unknownCost: "Bilinmiyor",
    partial: "eksik",
    total: "Toplam",
    discountNote: "Fiş düzeyi indirimler ürünlere dağıtılmaz; bu aralıktaki toplamı:",
    costNote: "Maliyet, satış gününe kadar girilen alış kayıtlarının ağırlıklı ortalamasıyla hesaplanır. Net satış KDV hariçtir.",
  },
  purchaseInvoices: {
    tab: "Alış faturaları",
    upload: "Fatura XML dosyası yükle",
    fetchQnb: "QNB'den çek",
    fetched: "QNB gelen kutusu tarandı.",
    fetchSummary: (result: { listed: number; imported: number; duplicates: number; skipped: number; stoppedEarly: boolean }) =>
      `QNB: ${result.listed} belge bulundu, ${result.imported} taslak oluştu, ${result.duplicates} zaten kayıtlıydı, ${result.skipped} belge alınamadı (iade veya bozuk).${result.stoppedEarly ? " Bağlantı sorunu nedeniyle durdu; tekrar çekebilirsiniz." : ""}`,
    status: "Durum",
    allStatuses: "Hepsi",
    listHeading: "Alış faturaları",
    detailHeading: "Fatura",
    loading: "Yükleniyor…",
    loadFailed: "Faturalar alınamadı.",
    lookupFailed: "Hammadde ve depo listesi alınamadı.",
    actionFailed: "İşlem tamamlanamadı.",
    empty: "Bu durumda fatura yok.",
    invoiceNumber: "Fatura no",
    issueDate: "Tarih",
    supplier: "Tedarikçi",
    lines: "Satır",
    unmappedLines: "Eşleşmemiş",
    netTotal: "Net tutar",
    open: "Aç",
    action: "İşlem",
    lineNo: "No",
    description: "Ürün",
    quantity: "Miktar",
    unitPrice: "Birim fiyat",
    lineNet: "Net tutar",
    stockItem: "Hammadde",
    choose: "Seçin",
    factor: "Çevrim katsayısı",
    map: "Eşleştir",
    notMapped: "Eşleşmedi",
    location: "Giriş yapılacak depo",
    approve: "Onayla ve stoğa gir",
    reject: "Reddet",
    imported: "Fatura taslak olarak alındı.",
    opened: "Fatura açıldı.",
    mapped: "Satır eşleştirildi; aynı ürün bu tedarikçinin diğer taslaklarında da eşleşti.",
    approved: "Fatura onaylandı ve stoğa girdi.",
    rejected: "Fatura reddedildi.",
    pickItem: "Önce bir hammadde seçin.",
    invalidFactor: "Çevrim katsayısı sıfırdan büyük bir sayı olmalı.",
    noSupplier: "Bu faturanın vergi numarasıyla kayıtlı bir tedarikçi yok; onaylamadan önce Satın alma bölümünden tedarikçiyi ekleyin.",
    unmappedWarning: (count: number) => `${count} satır henüz eşleşmedi; tümü eşleşmeden onaylanamaz.`,
    factorHint: "Çevrim katsayısı: fatura biriminin bir adedi kaç stok birimi eder (örneğin 1 koli = 24 litre ise 24).",
  },
  orderInvoices: {
    tab: "Online faturalar",
    heading: "Online sipariş fatura taslakları",
    from: "Başlangıç",
    to: "Bitiş",
    load: "Listele",
    loading: "Yükleniyor…",
    loadFailed: "Faturalar alınamadı.",
    detailFailed: "Fatura ayrıntısı alınamadı.",
    hint: "Hizmet tarihi aralığını seçip listeleyin.",
    empty: "Bu aralıkta fatura taslağı yok.",
    invalidRange: "Başlangıç tarihi bitişten sonra olamaz ve iki tarih de seçilmelidir.",
    tooLong: "Liste en çok 31 günü kapsayabilir.",
    serviceDate: "Hizmet tarihi",
    order: "Sipariş",
    platform: "Platform",
    status: "Durum",
    net: "Net",
    tax: "KDV",
    gross: "Toplam (KDV dahil)",
    detail: "Ayrıntı",
    show: "Göster",
    notSent: "Bunlar taslaktır; e-Arşiv'e gönderim henüz yapılmaz.",
    missingHeading: "Faturası henüz açılmamış siparişler",
    missingExplain: "Bu siparişlerin taslağı açılamadı. Ayarlar ekranında işletme bilgilerini girin; taslak kendiliğinden açılır. Süre dolmadan faturayı elle düzenlemeniz gerekir.",
    deliveredAt: "Teslim tarihi",
    daysLeft: "Kalan gün",
    detailHeading: "Fatura ayrıntısı",
    seller: "Satıcı",
    webAddress: "Satış yapılan adres",
    line: "Kalem",
    quantity: "Adet",
    taxRate: "KDV oranı",
  },
  system: {
    tab: "Sistem sağlığı",
    alertsHeading: "Etkin uyarılar",
    healthHeading: "Sağlıksız kontroller",
    noAlerts: "Etkin uyarı yok.",
    allHealthy: "Tüm kontroller sağlıklı.",
    acknowledge: "Gördüm",
    escalate: "Üst seviyeye taşı",
    suppress: "Sustur",
    resolve: "Çözüldü",
    resolutionReason: "Çözüm gerekçesi",
    reasonOptional: "Gerekçe (isteğe bağlı)",
    reasonRequired: "Çözüm gerekçesini yazın.",
    confirm: "Onayla",
    cancel: "Vazgeç",
    done: "Uyarı güncellendi.",
    target: "Hedef",
    status: "Durum",
    checkedAt: "Son kontrol",
    loading: "Yükleniyor…",
    loadFailed: "Veri alınamadı.",
    actionFailed: "İşlem tamamlanamadı.",
  },
  stock: {
    tab: "Stok",
    criticalHeading: "Kritik stok",
    varianceHeading: "Gerçek ve teorik kullanım farkı",
    itemsHeading: "Stok kalemleri",
    locationsHeading: "Stok konumları",
    from: "Başlangıç",
    to: "Bitiş",
    run: "Raporu getir",
    excluded: "Açılış veya kapanış sayımı eksik olduğu için dışarıda kalan kalem sayısı",
    code: "Kod",
    name: "Ad",
    type: "Tür",
    unit: "Birim",
    reorderPoint: "Yeniden sipariş noktası",
    location: "Konum",
    onHand: "Eldeki miktar",
    available: "Kullanılabilir",
    threshold: "Eşik",
    status: "Durum",
    actionsColumn: "İşlem",
    critical: "Kritik",
    ok: "Yeterli",
    actual: "Gerçek kullanım",
    theoretical: "Teorik kullanım",
    variance: "Fark",
    variancePercent: "Fark %",
    active: "Aktif",
    passive: "Pasif",
    defaultLocation: "Varsayılan konum",
    none: "Yok",
    newItem: "Yeni stok kalemi",
    newLocation: "Yeni stok konumu",
    add: "Ekle",
    itemAdded: "Stok kalemi eklendi.",
    locationAdded: "Stok konumu eklendi.",
    count: "Sayım gir",
    waste: "Fire kaydet",
    setReorder: "Sipariş noktası",
    countedQuantity: "Sayılan miktar",
    notes: "Not (isteğe bağlı)",
    wasteSource: "Fire nedeni türü",
    quantity: "Miktar",
    reason: "Açıklama",
    reorderHint: "Boş bırakırsanız eşik kaldırılır.",
    save: "Kaydet",
    cancel: "Vazgeç",
    countSaved: "Sayım kaydedildi.",
    wasteSaved: "Fire kaydedildi.",
    reorderSaved: "Yeniden sipariş noktası kaydedildi.",
    invalidNumber: "Geçerli bir sayı girin.",
    pickLocation: "Bir konum seçin.",
    noLocations: "Önce bir stok konumu ekleyin.",
    empty: "Kayıt yok.",
    loading: "Yükleniyor…",
    loadFailed: "Veri alınamadı.",
    actionFailed: "İşlem tamamlanamadı.",
  },
} as const;

/**
 * Cross-cutting actions. Per-workspace form action copy (cancel / confirm /
 * save labels) is migrated in a follow-up pass.
 */
export const commonActions = {
  refresh: "Yenile",
  retry: "Tekrar dene",
  reload: "Yeniden yükle",
} as const;

/**
 * Shared workspace state chrome. Every workspace renders the same offline /
 * unauthorized / error scaffolding; the titles and the generic fallbacks live
 * here so the wording stays identical (finding F-7).
 */
export const stateText = {
  offlineTitle: "Bağlantı yok",
  unauthorizedTitle: "Oturum gerekli",
  managerUnauthorizedTitle: "Yönetici oturumu gerekli",
  unexpectedError: "Beklenmeyen bir hata oluştu.",
  dismissMessage: "Mesajı kapat",
} as const;

/** Kitchen reprint decision flow. */
export const kitchenReprintText = {
  reasonRequired: "Süpervizör gerekçesi zorunlu.",
  reasonLabel: "Süpervizör gerekçesi",
} as const;

// --- Enum translation maps (re-exported from each feature's models.ts) ---

export const modeLabels: Record<SplitMode, string> = {
  EqualByPerson: "Eşit böl",
  ByItem: "Ürün / miktar",
  ByAmount: "Tutar gir",
};

/**
 * Bill lifecycle status labels. `billStatus` arrives from the server as a
 * plain string (ALKAROS.Billing.BillFoundation.BillState.ToString()), not a
 * narrow union, so this is a lookup with a neutral fallback (UI_STYLE_GUIDE
 * §3) rather than an exhaustive Record.
 */
export const billStatusLabels: Record<string, string> = {
  Open: "Açık",
  PartiallyAllocated: "Kısmen paylaştırıldı",
  Allocated: "Paylaştırıldı",
  PartiallyPaid: "Kısmen ödendi",
  Paid: "Ödendi",
  Cancelled: "İptal",
  Reopened: "Yeniden açıldı",
};

export const catalogEntityLabels: Record<CatalogEntityKind, string> = {
  categories: "Kategoriler",
  taxes: "Vergi profilleri",
  products: "Ürünler",
  modifierGroups: "Modifikatör grupları",
  modifiers: "Modifikatörler",
  prices: "Fiyatlar",
};

export const catalogAddLabels: Record<CatalogEntityKind, string> = {
  products: "Ürün",
  categories: "Kategori",
  taxes: "Vergi profili",
  modifierGroups: "Modifikatör grubu",
  modifiers: "Modifikatör",
  prices: "Fiyat",
};

/**
 * Found by an independent audit (2026-09-06): CatalogWorkspace.tsx's product
 * type <option> labels and two section headers were left untranslated (a
 * modifier-assignments heading and an effective-price-timeline heading) --
 * the <option value="..."> stays the wire enum (correctly English), but the
 * visible text must not.
 */
export const productTypeLabels: Record<string, string> = {
  MenuItem: "Menü ürünü",
  Modifier: "Modifikatör",
  AddOn: "Ek ürün",
  Packaging: "Ambalaj",
  ServiceItem: "Hizmet kalemi",
};

/**
 * V1-RMD-437 (V1-RMD-398 G-11): the sale path never reads the stock mode - an order is only accepted when the product
 * has a stock mapping (V1-RMD-143) - so the form no longer offers "Untracked"; older records still carry it and show
 * as a legacy value.
 */
export const stockModeLabels: Record<string, string> = {
  Untracked: "Takipsiz (eski kayıt)",
  QuantityTracked: "Miktar takipli",
  PortionTracked: "Porsiyon takipli",
  RecipeDerived: "Reçeteden",
};

/** V1-RMD-438: the price row subtitle showed the raw PriceType enum. */
export const priceTypeLabels: Record<string, string> = {
  SalePrice: "Satış fiyatı",
};

export const selectableStockModes = ["QuantityTracked", "PortionTracked", "RecipeDerived"] as const;

export const stockModeHint = "Siparişin onaylanması için ürünün stok eşlemesi olmalı.";

export const selectionTypeLabels: Record<string, string> = {
  SelectOne: "Tek seçim",
  SelectMany: "Çoklu seçim",
};

export const ticketStatusLabels: Record<KitchenTicket["status"], string> = {
  Queued: "Bekliyor",
  Accepted: "Kabul edildi",
  Preparing: "Hazırlanıyor",
  Ready: "Hazır",
  Cancelled: "İptal",
};

export const itemStatusLabels: Record<KitchenTicketItem["status"], string> = {
  Queued: "Bekliyor",
  Preparing: "Hazırlanıyor",
  Ready: "Hazır",
  Served: "Servis edildi",
  Cancelled: "İptal",
};

export const healthStatusLabels: Record<KitchenHealthSnapshot["databaseStatus"], string> = {
  Healthy: "Sağlıklı",
  Degraded: "Sınırlı",
  Unhealthy: "Sorunlu",
};

export const backupStatusLabels: Record<KitchenBackup["status"], string> = {
  InProgress: "Sürüyor",
  Completed: "Tamamlandı",
  Failed: "Başarısız",
};

export const tableStatusLabels: Record<TableStatus, string> = {
  Available: "Müsait",
  Occupied: "Dolu",
  Reserved: "Rezerve",
  // V1-TBL-010 (Semih's catch, 2026-09-12): the previous label read as a
  // hard "don't touch yet" while the actual system behaviour is the
  // opposite for the common case — a check sent to the cashier frees the
  // table for a new party IMMEDIATELY (SendCheckToCashierAsync,
  // V1-ORD-006), no staff action or confirmation required. The new label
  // reads as informational (recently vacated, might not be tidied yet)
  // rather than prohibitive.
  Cleaning: "Toplanıyor",
  OutOfService: "Servis dışı",
};

export const tableActionLabels: Partial<Record<TableAction, string>> = {
  SetOccupied: "Masayı aç",
  SetAvailable: "Müsait yap",
  Reserve: "Rezervasyon al",
  CancelReservation: "Rezervasyonu iptal et",
  ClaimReservation: "Rezervasyonu sahiplen",
  Transfer: "Masa değiştir",
  Merge: "Masaları birleştir",
  Unmerge: "Birleşimi ayır",
  SetCleaning: "Temizliğe al",
  SetOutOfService: "Servis dışı yap",
};

export const invoiceSettingsText = {
  kicker: "e-Arşiv fatura ayarları",
  heading: "İşletme bilgileri",
  loading: "Bilgiler okunuyor…",
  configured: "● Kayıtlı",
  notConfigured: "● Henüz girilmedi — online sipariş faturaları için gerekli",
  legalName: "Ticari ünvan",
  taxIdKind: "Numara türü",
  vkn: "Vergi kimlik numarası (VKN)",
  tckn: "T.C. kimlik numarası",
  taxIdNumber: "Vergi veya TC kimlik numarası",
  taxOffice: "Vergi dairesi",
  address: "Adres",
  district: "İlçe",
  city: "İl",
  email: "E-posta (isteğe bağlı)",
  save: "Kaydet",
  saving: "Kaydediliyor…",
  savedMessage: "İşletme bilgileri kaydedildi.",
} as const;
