<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ALKAROSTest>true</ALKAROSTest>
    <IsPackable>false</IsPackable>
    <RootNamespace>ALKAROS.Host.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Host\ALKAROS.Host.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\database\MigrationComposition\order.json" Link="Fixtures\order.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
