<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ALKAROSProjectKind>buildingblock</ALKAROSProjectKind>
    <RootNamespace>ALKAROS.Messaging</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IntegrationContracts\ALKAROS.IntegrationContracts.csproj" />
  </ItemGroup>

</Project>
