<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
    <RootNamespace>ALKAROS.TestHelpers</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" />
    <PackageReference Include="xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\BuildingBlocks\Transactions\ALKAROS.Transactions.csproj" />
  </ItemGroup>

</Project>