<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ALKAROSModule>true</ALKAROSModule>
    <RootNamespace>ALKAROS.Production</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../BuildingBlocks/ModuleComposition/ALKAROS.ModuleComposition.csproj" />
    <ProjectReference Include="../Inventory/ALKAROS.Inventory.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" />
  </ItemGroup>

</Project>
