<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ALKAROSTest>true</ALKAROSTest>
    <IsPackable>false</IsPackable>
    <RootNamespace>ALKAROS.TransactionOutboxIntegration.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\BuildingBlocks\TransactionOutboxIntegration\ALKAROS.TransactionOutboxIntegration.csproj" />
    <ProjectReference Include="..\..\..\src\BuildingBlocks\Messaging\ALKAROS.Messaging.csproj" />
    <ProjectReference Include="..\..\..\src\BuildingBlocks\Transactions\ALKAROS.Transactions.csproj" />
    <ProjectReference Include="..\TestHelpers\ALKAROS.TestHelpers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\database\migrations\V1\V1-FND-002\*.up.sql" Link="Fixtures\sql\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\..\database\migrations\V1\V1-FND-019\*.up.sql" Link="Fixtures\sql\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
