<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ALKAROSTest>true</ALKAROSTest>
    <IsPackable>false</IsPackable>
    <RootNamespace>ALKAROS.OnlineOrdering.Yemeksepeti.StatusSync.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../../src/Modules/OnlineOrdering/ALKAROS.OnlineOrdering.csproj" />
  </ItemGroup>

</Project>
